//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AxisDaily
    {
        public int AxisDailyId { get; set; }
        public int EngineeringId { get; set; }
        public string ext1 { get; set; }
        public string ext2 { get; set; }
        public string ext3 { get; set; }
        public string ext4 { get; set; }
        public string ext5 { get; set; }
        public string ext6 { get; set; }
        public string ext7 { get; set; }
        public string ext8 { get; set; }
        public string ext9 { get; set; }
        public string ext10 { get; set; }
        public string ext11 { get; set; }
    }
}
