//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class classes
    {
        public int classId { get; set; }
        public string className { get; set; }
        public string classDescrip { get; set; }
        public string parentId { get; set; }
        public string sortId { get; set; }
        public string depth { get; set; }
        public string childNum { get; set; }
        public string extension { get; set; }
        public string extension1 { get; set; }
        public string extension2 { get; set; }
        public string extension3 { get; set; }
    }
}
