//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Construction
    {
        public int ConstructionId { get; set; }
        public string SupportingId { get; set; }
        public string ProjectCost { get; set; }
        public string ConstructionUnit { get; set; }
        public string ConstructionLxr { get; set; }
        public string Phone { get; set; }
        public string Start { get; set; }
        public string Start_qht { get; set; }
        public string Start_jlxy { get; set; }
        public string Start_kgjc { get; set; }
        public string Start_zfzbj { get; set; }
        public string Hydropower { get; set; }
        public string Hydropower_ys { get; set; }
        public string Hydropower_gck { get; set; }
        public string MudFor { get; set; }
        public string MudFor_ys { get; set; }
        public string MudFor_gck { get; set; }
        public string Carpenter { get; set; }
        public string Carpenter_ys { get; set; }
        public string Carpenter_gck { get; set; }
        public string PaintFor { get; set; }
        public string PaintFor_ys { get; set; }
        public string PaintFor_gck { get; set; }
        public string CompletionOf { get; set; }
        public string CompletionOf_Ys { get; set; }
        public string CompletionOf_ts { get; set; }
        public string CompletionOf_bzj { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string CreateTime { get; set; }
    }
}
