//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily
    {
        public int ID { get; set; }
        public string userid { get; set; }
        public string ext1 { get; set; }
        public string ext2 { get; set; }
        public string ext3 { get; set; }
        public string ext4 { get; set; }
        public string ext5 { get; set; }
        public string ext6 { get; set; }
        public string ext7 { get; set; }
        public string ext8 { get; set; }
        public string ext9 { get; set; }
        public string ext10 { get; set; }
        public string ext11 { get; set; }
        public string ext12 { get; set; }
        public string ext13 { get; set; }
        public string ext14 { get; set; }
        public string ext15 { get; set; }
        public string ext16 { get; set; }
        public string ext17 { get; set; }
        public string ext18 { get; set; }
        public string ext19 { get; set; }
        public string ext20 { get; set; }
        public string ext21 { get; set; }
        public string ext22 { get; set; }
        public string ext23 { get; set; }
        public string ext24 { get; set; }
        public string ext25 { get; set; }
        public string ext26 { get; set; }
        public string ext27 { get; set; }
        public string ext28 { get; set; }
        public string ext29 { get; set; }
        public string ext30 { get; set; }
        public string ext31 { get; set; }
        public string ext32 { get; set; }
        public string ext33 { get; set; }
        public string ext34 { get; set; }
        public string ext35 { get; set; }
        public string ext36 { get; set; }
        public string ext37 { get; set; }
        public string ext38 { get; set; }
        public string ext39 { get; set; }
        public string ext40 { get; set; }
    }
}
