//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        public int DemandId { get; set; }
        public string Unit { get; set; }
        public string UserId { get; set; }
        public string StyleId { get; set; }
        public string AreaId { get; set; }
        public string Property { get; set; }
        public string AreaSize { get; set; }
        public string Other { get; set; }
        public string Aprogram { get; set; }
        public string Earnest { get; set; }
        public string Bprogram { get; set; }
        public string Balancedue { get; set; }
        public string ElectronicB { get; set; }
        public string Address { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Jtrk { get; set; }
        public string Ys { get; set; }
        public string CreateTime { get; set; }
    }
}
