//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineering
    {
        public int engineeringId { get; set; }
        public Nullable<int> demandId { get; set; }
        public string userName { get; set; }
        public string userPhone { get; set; }
        public string userAddress { get; set; }
        public string stageOneState { get; set; }
        public string stageTwoState { get; set; }
        public string stageThreeState { get; set; }
        public string stageFourState { get; set; }
        public string stageFiveState { get; set; }
        public string stageSexState { get; set; }
        public string stageSevenState { get; set; }
        public string extension { get; set; }
        public string extension1 { get; set; }
        public string extension2 { get; set; }
        public string extension3 { get; set; }
        public string extension4 { get; set; }
        public string extension5 { get; set; }
        public string extension6 { get; set; }
        public string extension7 { get; set; }
        public string extension8 { get; set; }
        public string createTime { get; set; }
    }
}
