//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindProduct
    {
        public int findProductId { get; set; }
        public string productName { get; set; }
        public string unit { get; set; }
        public string ProductUrl { get; set; }
        public string productImg { get; set; }
        public string pattern { get; set; }
        public string style { get; set; }
        public string cz { get; set; }
        public string modelling { get; set; }
        public string size { get; set; }
        public string zBigClass { get; set; }
        public string bigClass { get; set; }
        public string smailClass { get; set; }
        public string roomId { get; set; }
        public string types { get; set; }
        public string userId { get; set; }
        public string des { get; set; }
        public string extension { get; set; }
        public string extension1 { get; set; }
        public string extension2 { get; set; }
        public string extension3 { get; set; }
        public string extension4 { get; set; }
        public string extension5 { get; set; }
        public string extension6 { get; set; }
        public string extension7 { get; set; }
        public string extension8 { get; set; }
        public string extension9 { get; set; }
        public string extension10 { get; set; }
        public string extension11 { get; set; }
        public string extension12 { get; set; }
        public string extension13 { get; set; }
        public string extension14 { get; set; }
        public string createTime { get; set; }
    }
}
