//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindProject
    {
        public int UpProjectId { get; set; }
        public string types { get; set; }
        public string bigClass { get; set; }
        public string smailClass { get; set; }
        public string num { get; set; }
        public string unitMin { get; set; }
        public string unitMan { get; set; }
        public string zcMin { get; set; }
        public string zcMax { get; set; }
        public string price { get; set; }
        public string extension { get; set; }
        public string extension1 { get; set; }
        public string extension2 { get; set; }
        public string extension3 { get; set; }
        public string extension4 { get; set; }
        public string extension5 { get; set; }
        public string extension6 { get; set; }
        public string extension7 { get; set; }
        public string extension8 { get; set; }
        public string extension9 { get; set; }
    }
}
