//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MJ100_HOUSE
    {
        public int ID { get; set; }
        public string HOUSE_NAME { get; set; }
        public int S_PROVINCE_PROVINCEID { get; set; }
        public int S_CITY_CITYID { get; set; }
        public int S_DISTRICT_DISTRICTID { get; set; }
        public string HOUSE_IMAGE { get; set; }
        public string HOUSE_PREMISES { get; set; }
        public string HOUSE_AREA { get; set; }
        public string HOUSE_TYPE { get; set; }
        public string HOUSE_LONGITUDE_LATITUDE { get; set; }
        public int IS_TAG { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    }
}
