//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MJ100_HOUSE_TAG
    {
        public int ID { get; set; }
        public int HOUSE_ID { get; set; }
        public string TOILET { get; set; }
        public string BEDROOM { get; set; }
        public string DINING_ROOM { get; set; }
        public string KITCHEN { get; set; }
        public string OUTDOOR { get; set; }
        public string OTHER { get; set; }
        public string REMARK { get; set; }
        public System.DateTime CAREATE_DATE { get; set; }
        public string tags { get; set; }
    }
}
