//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class money
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string dayMoney { get; set; }
        public string state { get; set; }
        public string dayTime { get; set; }
        public string extension1 { get; set; }
        public string extension2 { get; set; }
        public string extension3 { get; set; }
        public string extension4 { get; set; }
        public string createTime { get; set; }
    }
}
