//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPty
    {
        public int ProjectTpId { get; set; }
        public string ProjectTpName { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
    }
}
