//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rm_Style_ys
    {
        public int did { get; set; }
        public string roomName { get; set; }
        public string roomDesp { get; set; }
        public string frontCover { get; set; }
        public string aidColor { get; set; }
        public Nullable<int> likeNum { get; set; }
        public Nullable<int> commentNum { get; set; }
        public string Extension { get; set; }
        public string userId { get; set; }
        public string Extension5 { get; set; }
        public string color { get; set; }
        public string href { get; set; }
        public string createTime { get; set; }
        public string Extension4 { get; set; }
        public string price { get; set; }
        public string tgPrice { get; set; }
        public string stage { get; set; }
        public string LoginName { get; set; }
        public string HeadImage { get; set; }
    }
}
