//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int did { get; set; }
        public string roomName { get; set; }
        public string roomId { get; set; }
        public string styleId { get; set; }
        public string color { get; set; }
        public string aidColor { get; set; }
        public string unit { get; set; }
        public string budget { get; set; }
        public string structure { get; set; }
        public string roomDesp { get; set; }
        public string tagDesp { get; set; }
        public string frontCover { get; set; }
        public Nullable<int> likeNum { get; set; }
        public Nullable<int> commentNum { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string Extension4 { get; set; }
        public string Extension5 { get; set; }
        public string Extension6 { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> S { get; set; }
        public Nullable<int> B { get; set; }
        public string Types { get; set; }
        public string Extension7 { get; set; }
        public string Extension8 { get; set; }
        public string Extension9 { get; set; }
        public string Extension10 { get; set; }
        public string Extension11 { get; set; }
        public string Extension12 { get; set; }
        public string Extension13 { get; set; }
        public string Extension14 { get; set; }
        public string Extension15 { get; set; }
        public string rzzh { get; set; }
        public string rqzq { get; set; }
        public string rqzh { get; set; }
        public string rmpt { get; set; }
        public string rpmt { get; set; }
        public string szhdbq { get; set; }
        public string zzhdbq { get; set; }
        public string qzhdbq { get; set; }
        public string createTime { get; set; }
    }
}
