//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public Nullable<int> DemandId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<System.DateTime> BeginPhase1 { get; set; }
        public Nullable<System.DateTime> EndPhase1 { get; set; }
        public Nullable<System.DateTime> BeginCheck1 { get; set; }
        public Nullable<System.DateTime> EndCheck1 { get; set; }
        public string Time1 { get; set; }
        public Nullable<System.DateTime> BeginPhase2 { get; set; }
        public Nullable<System.DateTime> EndPhase2 { get; set; }
        public Nullable<System.DateTime> BeginCheck2 { get; set; }
        public Nullable<System.DateTime> EndCheck2 { get; set; }
        public string Time2 { get; set; }
        public Nullable<System.DateTime> BeginPhase3 { get; set; }
        public Nullable<System.DateTime> EndPhase3 { get; set; }
        public Nullable<System.DateTime> BeginCheck3 { get; set; }
        public Nullable<System.DateTime> EndCheck3 { get; set; }
        public string Time3 { get; set; }
        public Nullable<System.DateTime> BeginPhase4 { get; set; }
        public Nullable<System.DateTime> EndPhase4 { get; set; }
        public Nullable<System.DateTime> BeginCheck4 { get; set; }
        public Nullable<System.DateTime> EndCheck4 { get; set; }
        public string Time4 { get; set; }
        public Nullable<System.DateTime> BeginPhase5 { get; set; }
        public Nullable<System.DateTime> EndPhase5 { get; set; }
        public Nullable<System.DateTime> BeginCheck5 { get; set; }
        public Nullable<System.DateTime> EndCheck5 { get; set; }
        public string Time5 { get; set; }
        public Nullable<System.DateTime> BeginPhase6 { get; set; }
        public Nullable<System.DateTime> EndPhase6 { get; set; }
        public Nullable<System.DateTime> BeginCheck6 { get; set; }
        public Nullable<System.DateTime> EndCheck6 { get; set; }
        public string Time6 { get; set; }
        public Nullable<int> CurrentPhase { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string Extension4 { get; set; }
        public string Extension5 { get; set; }
        public string Extension6 { get; set; }
        public string Extension7 { get; set; }
        public string Extension8 { get; set; }
        public string Extension9 { get; set; }
        public string Extension10 { get; set; }
    }
}
