//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showroom
    {
        public int ShowroomId { get; set; }
        public string UnitId { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public string ProjectId { get; set; }
        public string ProductId { get; set; }
        public string StyleId { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string Extension4 { get; set; }
        public string Extension5 { get; set; }
        public Nullable<int> Extension6 { get; set; }
        public string Extension7 { get; set; }
        public string Extension8 { get; set; }
        public string Extension9 { get; set; }
        public string Extension10 { get; set; }
        public string Extension11 { get; set; }
        public string Extension12 { get; set; }
        public string Extension13 { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> S { get; set; }
        public Nullable<int> B { get; set; }
        public string CreateTime { get; set; }
    }
}
