//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public int stageId { get; set; }
        public string startTime { get; set; }
        public string finishTime { get; set; }
        public string checkTime { get; set; }
        public string oneItemClState { get; set; }
        public string oneItemClCon { get; set; }
        public string oneItemClPic { get; set; }
        public string oneItemClExt { get; set; }
        public string oneItemClExt1 { get; set; }
        public string oneItemGcState { get; set; }
        public string oneItemGcCon { get; set; }
        public string oneItemGcPic { get; set; }
        public string oneItemGcExt { get; set; }
        public string oneItemGcExt1 { get; set; }
        public string twoItemClState { get; set; }
        public string twoItemClCon { get; set; }
        public string twoItemClPic { get; set; }
        public string twoItemClExt { get; set; }
        public string twoItemClExt1 { get; set; }
        public string twoItemGcState { get; set; }
        public string twoItemGcCon { get; set; }
        public string twoItemGcPic { get; set; }
        public string twoItemGcExt { get; set; }
        public string twoItemGcExt1 { get; set; }
        public string threeItemClState { get; set; }
        public string threeItemClCon { get; set; }
        public string threeItemClPic { get; set; }
        public string threeItemClExt { get; set; }
        public string threeItemClExt1 { get; set; }
        public string threeItemGcState { get; set; }
        public string threeItemGcCon { get; set; }
        public string threeItemGcPic { get; set; }
        public string threeItemGcExt { get; set; }
        public string threeItemGcExt1 { get; set; }
        public string fourItemClState { get; set; }
        public string fourItemClCon { get; set; }
        public string fourItemClPic { get; set; }
        public string fourItemClExt { get; set; }
        public string fourItemClExt1 { get; set; }
        public string fourItemGcState { get; set; }
        public string fourItemGcCon { get; set; }
        public string fourItemGcPic { get; set; }
        public string fourItemGcExt { get; set; }
        public string fourItemGcExt1 { get; set; }
        public string fiveItemClState { get; set; }
        public string fiveItemClCon { get; set; }
        public string fiveItemClPic { get; set; }
        public string fiveItemClExt { get; set; }
        public string fiveItemClExt1 { get; set; }
        public string fiveItemGcState { get; set; }
        public string fiveItemGcCon { get; set; }
        public string fiveItemGcPic { get; set; }
        public string fiveItemGcExt { get; set; }
        public string fiveItemGcExt1 { get; set; }
        public string sexItemClState { get; set; }
        public string sexItemClCon { get; set; }
        public string sexItemClPic { get; set; }
        public string sexItemClExt { get; set; }
        public string sexItemClExt1 { get; set; }
        public string sexItemGcState { get; set; }
        public string sexItemGcCon { get; set; }
        public string sexItemGcPic { get; set; }
        public string sexItemGcExt { get; set; }
        public string sexItemGcExt1 { get; set; }
        public Nullable<int> EngineeringId { get; set; }
        public string stageType { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string Extension4 { get; set; }
        public string Extension5 { get; set; }
        public string Extension6 { get; set; }
        public string Extension7 { get; set; }
        public string Extension8 { get; set; }
        public string createTime { get; set; }
    }
}
