//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class suu
    {
        public Nullable<int> H { get; set; }
        public Nullable<int> B { get; set; }
        public Nullable<int> S { get; set; }
        public string Description { get; set; }
        public string Extension7 { get; set; }
        public string Extension { get; set; }
        public string hxt { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string Extension4 { get; set; }
        public string Extension5 { get; set; }
        public Nullable<int> Extension6 { get; set; }
        public string ProductId { get; set; }
        public string ProjectId { get; set; }
        public int ShowroomId { get; set; }
        public string StyleId { get; set; }
        public string UnitId { get; set; }
        public string UserId { get; set; }
        public string Extension9 { get; set; }
        public string Extension10 { get; set; }
        public string AreaSize { get; set; }
        public Nullable<long> DistrictID { get; set; }
        public string DistrictName { get; set; }
        public string Property { get; set; }
        public string UnitName { get; set; }
        public string UnitTypeName { get; set; }
        public string UnitTypeId { get; set; }
        public string UserName { get; set; }
        public string UserType { get; set; }
    }
}
