//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public string UnitTypeId { get; set; }
        public string AreaId { get; set; }
        public string Property { get; set; }
        public string AreaSize { get; set; }
        public string Con { get; set; }
        public string OperatorId { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string CreateTime { get; set; }
    }
}
