//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoom
    {
        public int id { get; set; }
        public string userId { get; set; }
        public string demandId { get; set; }
        public Nullable<int> roomTpId { get; set; }
        public string roomName { get; set; }
        public string roomId { get; set; }
        public string extension { get; set; }
        public string extension1 { get; set; }
        public string extension2 { get; set; }
        public string extension3 { get; set; }
        public string extension4 { get; set; }
        public string UserRoomaidColors { get; set; }
        public string structures { get; set; }
        public string userRoomDes { get; set; }
        public string userRoomTag { get; set; }
        public string extension55 { get; set; }
        public string extension56 { get; set; }
        public string extension57 { get; set; }
        public string extension58 { get; set; }
        public string szq { get; set; }
        public string szh { get; set; }
        public string zzq { get; set; }
        public string zzh { get; set; }
        public string qzq { get; set; }
        public string qzh { get; set; }
        public string mpt { get; set; }
        public string pmt { get; set; }
        public string LfPmt { get; set; }
        public string LfPic { get; set; }
        public string createTime { get; set; }
    }
}
