//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Stype
    {
        public string StypeName { get; set; }
        public int wSroomId { get; set; }
        public int ShoowRoomId { get; set; }
        public string jtId { get; set; }
        public string ryId { get; set; }
        public string ysfw { get; set; }
        public string zxfg { get; set; }
        public string qt { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string Extension4 { get; set; }
        public string Extension5 { get; set; }
        public string Extension6 { get; set; }
        public string Extension7 { get; set; }
        public string Color { get; set; }
        public string aidColor { get; set; }
        public string CreateTime { get; set; }
        public string projectTypeName { get; set; }
    }
}
