//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DabaoqianPro
    {
        public string Netprice { get; set; }
        public string Pname { get; set; }
        public string Unit { get; set; }
        public string extension { get; set; }
        public int prid { get; set; }
        public string pvid { get; set; }
        public string shu { get; set; }
        public string zhi { get; set; }
        public Nullable<int> MOID { get; set; }
        public string Moname { get; set; }
        public string CName { get; set; }
    }
}
