//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_WhereShowRoom_smt
    {
        public int SroomPId { get; set; }
        public string ProductId { get; set; }
        public string Num { get; set; }
        public string Price { get; set; }
        public string ProjectTypeId { get; set; }
        public string ShowroomId { get; set; }
        public string Extension { get; set; }
        public string Extension3 { get; set; }
        public string Pname { get; set; }
        public string Netprice { get; set; }
        public string pic { get; set; }
        public string Unit { get; set; }
        public string Extension1 { get; set; }
    }
}
