//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_SupportingUserStyle
    {
        public string CreateTime { get; set; }
        public string Description { get; set; }
        public string SupportingType { get; set; }
        public int SupportingId { get; set; }
        public string LoginName { get; set; }
        public string StypeName { get; set; }
    }
}
