//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProductsWalls
    {
        public Nullable<int> num { get; set; }
        public int PID { get; set; }
        public string Pname { get; set; }
        public Nullable<decimal> Marketprice { get; set; }
        public Nullable<decimal> Netprice { get; set; }
        public string extension { get; set; }
        public Nullable<int> CID { get; set; }
        public string Pmodel { get; set; }
        public Nullable<int> MOID { get; set; }
        public Nullable<int> BID { get; set; }
    }
}
