//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Demand
    {
        public string jlId { get; set; }
        public string pId { get; set; }
        public string UserId { get; set; }
        public int DemandShowroomId { get; set; }
        public string ProjectId { get; set; }
        public string ProductId { get; set; }
        public string Extension2 { get; set; }
        public string Extension6 { get; set; }
        public string Extension9 { get; set; }
        public string Extension { get; set; }
        public string Extension10 { get; set; }
        public string Extension16 { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string fk { get; set; }
        public Nullable<int> xu { get; set; }
        public string LoginName { get; set; }
        public string UserMPhone { get; set; }
        public string htm { get; set; }
        public string htsj { get; set; }
        public string ms { get; set; }
        public string ztpmt { get; set; }
        public string OrderId { get; set; }
        public string CreateTime { get; set; }
    }
}
