//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SellerByBrand
    {
        public int SID { get; set; }
        public string Sname { get; set; }
        public string Stelephone { get; set; }
        public string Saddress { get; set; }
        public string Sjoin { get; set; }
        public string Sfree { get; set; }
        public string Szp { get; set; }
        public string extension { get; set; }
        public string extension1 { get; set; }
        public string extension2 { get; set; }
        public string extension3 { get; set; }
        public string extension4 { get; set; }
        public string Bname { get; set; }
        public Nullable<int> CID { get; set; }
        public string CName { get; set; }
        public Nullable<int> MCID { get; set; }
        public string Mcname { get; set; }
    }
}
