//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ReportItem_ReportTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Pic { get; set; }
        public string Index { get; set; }
        public string ParentId { get; set; }
        public string TableType { get; set; }
        public string CreateTime { get; set; }
        public string ProjectManager { get; set; }
        public string InspectorGeneral { get; set; }
        public string Client { get; set; }
    }
}
