//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_UserRoom_rm
    {
        public int id { get; set; }
        public string demandId { get; set; }
        public string userId { get; set; }
        public Nullable<int> roomTpId { get; set; }
        public string pic { get; set; }
        public string rmId { get; set; }
        public string rName { get; set; }
        public string structures { get; set; }
        public string zhu { get; set; }
        public string ext56 { get; set; }
        public string ext57 { get; set; }
        public string fgs { get; set; }
        public string mjs { get; set; }
        public string userRoomTag { get; set; }
        public string userRoomDes { get; set; }
        public string tim { get; set; }
        public string szq { get; set; }
        public string szh { get; set; }
        public string zzq { get; set; }
        public string zzh { get; set; }
        public string qzq { get; set; }
        public string qzh { get; set; }
        public string pmt { get; set; }
        public string mpt { get; set; }
        public string LfPmt { get; set; }
        public string LfPic { get; set; }
        public string colorTp { get; set; }
        public Nullable<int> did { get; set; }
        public string roomName { get; set; }
        public string roomId { get; set; }
        public string styleId { get; set; }
        public string color { get; set; }
        public string aidColor { get; set; }
        public string unit { get; set; }
        public string budget { get; set; }
        public string structure { get; set; }
        public string roomDesp { get; set; }
        public string tagDesp { get; set; }
        public string frontCover { get; set; }
        public Nullable<int> likeNum { get; set; }
        public Nullable<int> commentNum { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string Extension4 { get; set; }
        public string Extension5 { get; set; }
        public string Extension6 { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> S { get; set; }
        public Nullable<int> B { get; set; }
        public string Types { get; set; }
        public string Extension7 { get; set; }
        public string Extension8 { get; set; }
        public string Extension9 { get; set; }
        public string Extension10 { get; set; }
        public string Extension11 { get; set; }
        public string Extension12 { get; set; }
        public string Extension13 { get; set; }
        public string Extension14 { get; set; }
        public string Extension15 { get; set; }
        public string createTime { get; set; }
        public string rqzq { get; set; }
        public string rqzh { get; set; }
        public string rmpt { get; set; }
        public string rpmt { get; set; }
        public string szhdbq { get; set; }
        public string zzhdbq { get; set; }
        public string qzhdbq { get; set; }
        public string Expr1 { get; set; }
        public string Description { get; set; }
        public string LoginName { get; set; }
        public string HeadImage { get; set; }
    }
}
