//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderMessage
    {
        public int Id { get; set; }
        public string DemandId { get; set; }
        public string OrderId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string OrderTime { get; set; }
        public string MNumber { get; set; }
        public string PayState { get; set; }
        public string PayAdvance { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string OrderDate { get; set; }
        public string LoginName { get; set; }
        public string UserMPhone { get; set; }
    }
}
