//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProductsByMclassify
    {
        public int PID { get; set; }
        public string Pcolor { get; set; }
        public string UrlID { get; set; }
        public string Pname { get; set; }
        public string Marketprice { get; set; }
        public string Netprice { get; set; }
        public string Pmodel { get; set; }
        public string extension { get; set; }
        public string Fname { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> MOID { get; set; }
        public Nullable<int> BID { get; set; }
        public string Evaluation { get; set; }
        public int MCID { get; set; }
        public string Bname { get; set; }
        public string CName { get; set; }
        public Nullable<bool> Pstate { get; set; }
        public string Mcname { get; set; }
        public Nullable<int> MID { get; set; }
        public Nullable<int> PVID { get; set; }
        public Nullable<int> likeNum { get; set; }
        public Nullable<int> comNum { get; set; }
        public Nullable<int> extension5 { get; set; }
        public Nullable<int> num { get; set; }
    }
}
