//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RandUsers
    {
        public int UserId { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public string UserPhone { get; set; }
        public string UserMPhone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string HeadImage { get; set; }
        public string LoginTime { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string Extension4 { get; set; }
        public string Extension5 { get; set; }
        public string Extension6 { get; set; }
        public Nullable<int> Extension7 { get; set; }
        public string Extension8 { get; set; }
        public string CreateTime { get; set; }
    }
}
