//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_OrderMessageT
    {
        public int TententId { get; set; }
        public string Tkey { get; set; }
        public string UserId { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string CreateTime { get; set; }
        public string Extension4 { get; set; }
        public string Extension5 { get; set; }
        public string Extension6 { get; set; }
        public string Extension7 { get; set; }
        public string District { get; set; }
        public string Validity { get; set; }
        public string DemandId { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<double> qdPrice { get; set; }
    }
}
