//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_pType
    {
        public Nullable<long> ROWID { get; set; }
        public int ProductId { get; set; }
        public string ProductType { get; set; }
        public string Unit { get; set; }
        public string ProductAmount { get; set; }
        public string Price { get; set; }
        public string TypeId { get; set; }
        public string Type { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string CreateTime { get; set; }
        public string ProjectTpName { get; set; }
    }
}
