//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DailyList
    {
        public int engineeringId { get; set; }
        public string extension1 { get; set; }
        public Nullable<int> demandId { get; set; }
        public string userName { get; set; }
        public string userPhone { get; set; }
        public string userAddress { get; set; }
        public string extension8 { get; set; }
        public string createTime { get; set; }
        public string Extension2 { get; set; }
        public string shzy { get; set; }
    }
}
