//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DabiaoqianProducts
    {
        public string Bname { get; set; }
        public string Pname { get; set; }
        public string extension { get; set; }
        public string Pmodel { get; set; }
        public string Marketprice { get; set; }
        public string Netprice { get; set; }
        public string Unit { get; set; }
        public string img { get; set; }
        public Nullable<bool> Pstate { get; set; }
        public string Fname { get; set; }
        public int PID { get; set; }
        public Nullable<int> BID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<System.DateTime> type { get; set; }
        public Nullable<int> PRID { get; set; }
        public Nullable<int> MOID { get; set; }
        public string guige { get; set; }
    }
}
