//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProductRoom
    {
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public string UnitTypeId { get; set; }
        public string AreaId { get; set; }
        public string Property { get; set; }
        public string AreaSize { get; set; }
        public string Con { get; set; }
        public string OperatorId { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string CreateTime { get; set; }
        public Nullable<long> DistrictID { get; set; }
        public string DistrictName { get; set; }
        public Nullable<long> CityID { get; set; }
        public string CityName { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<long> ProvinceID { get; set; }
        public string UnitTypeName { get; set; }
        public int ShowroomId { get; set; }
        public string Description { get; set; }
        public string ProductId { get; set; }
        public int SroomPId { get; set; }
        public string se { get; set; }
    }
}
