//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ComUsSm
    {
        public int CommentId { get; set; }
        public string CommentCon { get; set; }
        public string UserId { get; set; }
        public string TypeId { get; set; }
        public string Type { get; set; }
        public string Extension { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string CreateTime { get; set; }
        public string Ext3 { get; set; }
        public string Ext4 { get; set; }
        public string LoginName { get; set; }
        public string HeadImage { get; set; }
    }
}
