//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ModelclasByMclassify
    {
        public int MOID { get; set; }
        public string Moname { get; set; }
        public int CID { get; set; }
        public string CName { get; set; }
        public int MCID { get; set; }
        public string Mcname { get; set; }
    }
}
