//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ShenQi
    {
        public string LoginName { get; set; }
        public string UserMPhone { get; set; }
        public int sqId { get; set; }
        public string userId { get; set; }
        public string sfz { get; set; }
        public string yhk { get; set; }
        public string fczm { get; set; }
        public string gzsrzm { get; set; }
        public string zfzxht { get; set; }
        public string gcyss { get; set; }
        public string fwzlbz { get; set; }
        public string cphgz { get; set; }
        public string extension1 { get; set; }
        public string extension { get; set; }
    }
}
