//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Seach
    {
        public string name { get; set; }
        public string tp { get; set; }
        public string dess { get; set; }
        public string img { get; set; }
        public string pp { get; set; }
        public int id { get; set; }
        public Nullable<int> likeNums { get; set; }
        public Nullable<int> plNum { get; set; }
        public string price { get; set; }
        public string sjs { get; set; }
        public string zb { get; set; }
        public string createTime { get; set; }
    }
}
