//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Demandsp
    {
        public string CName { get; set; }
        public int SroomPId { get; set; }
        public string DemandShowroomId { get; set; }
        public string Bname { get; set; }
        public string Num { get; set; }
        public string ProductId { get; set; }
        public string Price { get; set; }
        public string Pmodel { get; set; }
        public string Unit { get; set; }
        public string Netprice { get; set; }
        public string extension { get; set; }
        public string Pname { get; set; }
        public Nullable<int> PRID { get; set; }
        public string UrlID { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Extension3 { get; set; }
        public string Extension5 { get; set; }
        public string Extension6 { get; set; }
        public string CreateTime { get; set; }
        public string mojd { get; set; }
        public string mojd2 { get; set; }
        public string cljd { get; set; }
        public string cljd2 { get; set; }
    }
}
