//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_sp
    {
        public Nullable<int> MOID { get; set; }
        public string showRoomId { get; set; }
        public string Bname { get; set; }
        public string Extension3 { get; set; }
        public string Extension1 { get; set; }
        public string tp { get; set; }
        public int SroomPId { get; set; }
        public string Num { get; set; }
        public string ProductId { get; set; }
        public string Price { get; set; }
        public string fjlx { get; set; }
        public string Pmodel { get; set; }
        public string Unit { get; set; }
        public string ProjectTypeId { get; set; }
        public string projectTypeName { get; set; }
        public string Netprice { get; set; }
        public string extension { get; set; }
        public string Marketprice { get; set; }
        public string Pname { get; set; }
        public string gg { get; set; }
        public string CName { get; set; }
        public string Moname { get; set; }
    }
}
