//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SelectDesignByUserid
    {
        public int Id { get; set; }
        public string DemandId { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> engineeringId { get; set; }
        public string userPhone { get; set; }
        public string userAddress { get; set; }
        public string extension2 { get; set; }
        public string extension4 { get; set; }
        public string extension5 { get; set; }
        public string HeadImage { get; set; }
        public string UserMPhone { get; set; }
    }
}
